### ISSUE TITLE
Do you have plan to publish this repo to Hex.pm?

### ISSUE THREAD

**Issue by c4710n** [jonnystorm/ordered-map-elixir#3]
This is a good library that has the same interface with native Map.

But in Hex.pm, I can't find this repo. Do you have plan to publish this repo to Hex.pm?

**Comment by jonnystorm** [comment]
@c4710n Thanks for contributing!

I hadn't planned to, but that's a good idea! Incidentally, OTP has [orddict](http://erlang.org/doc/man/orddict.html), of which I was ignorant when I wrote this library, but it's nice having an Elixir-centric variant at hand.

I'll make some time to register this library with Hex, this week, and I'll let you know once it's up.

**Comment by c4710n** [comment]
You have contributed your time for the core functionality. And, I would like contribute my time, too.

So, I create a PR for publishing - #4 . The basic usage is: 
1. change `@version`
2. run `mix publish`, then it will publish package to hex.pm, create tag and push to repo.

Feel free to use it, and feel free to close it if you don't need it.

**Comment by jonnystorm** [comment]
[Done!](https://hex.pm/packages/ordered_map) Thanks @c4710n !
