### ISSUE TITLE
Problem in OrderedMap.delete

### ISSUE THREAD

**Issue by mmower** [jonnystorm/ordered-map-elixir#7]
Hi.

Also we've spotted a bug in the implementation of `OrderedMap.delete`

https://github.com/jonnystorm/ordered-map-elixir/blob/040e9ddbebaf7e527c1c595e3a9df2bf568a0e73/lib/ordered_map.ex#L75

Where if the value is `false` it won't work. Suggest `Map.has_key?(map, key)` instead.

**Comment by jonnystorm** [comment]
Thanks again, @mmower!

That should be fixed in v0.0.6. Please let me know if you have any more trouble.
